name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run lint
      run: ./gradlew lint
    - name: Run detekt
      run: ./gradlew detekt
    - name: Run ktlint
      run: ./gradlew ktlintCheck

# Running 1,5h and crash witch error https://github.com/iamtihonov/TemplateProject2/actions/runs/6852984534
# and use last api-level https://github.com/ReactiveCircus/android-emulator-runner
#    - name: Run Instrumentation Tests (reactivecircus)
#      uses: reactivecircus/android-emulator-runner@v2
#      with:
#        api-level: 23
#        target: default
#        arch: x86
#        profile: Nexus 6
#        script: ./gradlew connectedCheck --stacktrace

